# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avicola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinario',
            name='tipo',
            field=models.CharField(choices=[('experto', 'Experto'), ('auxiliar', 'Auxiliar')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
