# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avicola', '0002_veterinario_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallina',
            old_name='fecha_nacimineto',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='cantidadGallinas',
            new_name='cantidad_gallinas',
        ),
    ]
