# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avicola', '0002_galpon_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='tipo',
            field=models.CharField(choices=[('administrativo', 'Administrativo'), ('produccion', 'Produccion')], default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nivelPro',
            field=models.CharField(choices=[('tecnico', 'Tecnico'), ('tecnologo', 'Tecnologo'), ('profesional', 'Profesional'), ('maestria', 'Maestria'), ('doctorado', 'Doctorado')], max_length=100),
        ),
        migrations.AlterField(
            model_name='gallina',
            name='raza',
            field=models.CharField(choices=[('black_rock', 'Black rock'), ('speckledy', 'Speckledy')], max_length=100),
        ),
    ]
