# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avicola', '0003_auto_20170312_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='intensidad_horaria',
            field=models.IntegerField(default=1, help_text='Cantidad de horas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha',
            field=models.DateField(),
        ),
    ]
