# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avicola', '0003_auto_20170312_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('gallina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avicola.Gallina')),
            ],
        ),
    ]
