# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avicola', '0004_auto_20170312_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='granja',
            old_name='cantGallinas',
            new_name='capacidad_max_gallinas',
        ),
    ]
