# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avicola', '0005_auto_20170312_2117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventoGranja',
            new_name='EventoGalpon',
        ),
        migrations.RemoveField(
            model_name='eventogalpon',
            name='granja',
        ),
        migrations.AddField(
            model_name='eventogalpon',
            name='galpon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='avicola.Galpon'),
            preserve_default=False,
        ),
    ]
