# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avicola', '0006_auto_20170312_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galpon',
            old_name='capacidad',
            new_name='capacidad_max_gallinas',
        ),
        migrations.RenameField(
            model_name='granja',
            old_name='responsable',
            new_name='jefe',
        ),
        migrations.AddField(
            model_name='galpon',
            name='responsable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='avicola.Empleado'),
            preserve_default=False,
        ),
    ]
