# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avicola', '0008_remove_galpon_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='beneficio_cooperativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gallina',
            name='codigo',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lote',
            name='codigo',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
