# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avicola', '0010_remove_gallina_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallina',
            name='novedad',
        ),
    ]
